	.align 2
	.global ProgrammableWaveData_86DD6D0
ProgrammableWaveData_86DD6D0:
	.incbin "sound/programmable_wave_samples/086DD6D0.pcm"

	.align 2
	.global ProgrammableWaveData_86DD6E0
ProgrammableWaveData_86DD6E0:
	.incbin "sound/programmable_wave_samples/086DD6E0.pcm"

	.align 2
	.global ProgrammableWaveData_86DD6F0
ProgrammableWaveData_86DD6F0:
	.incbin "sound/programmable_wave_samples/086DD6F0.pcm"

	.align 2
	.global ProgrammableWaveData_86DD700
ProgrammableWaveData_86DD700:
	.incbin "sound/programmable_wave_samples/086DD700.pcm"

	.align 2
	.global ProgrammableWaveData_86DD710
ProgrammableWaveData_86DD710:
	.incbin "sound/programmable_wave_samples/086DD710.pcm"

	.align 2
	.global ProgrammableWaveData_86DD720
ProgrammableWaveData_86DD720:
	.incbin "sound/programmable_wave_samples/086DD720.pcm"

	.align 2
	.global ProgrammableWaveData_86DD730
ProgrammableWaveData_86DD730:
	.incbin "sound/programmable_wave_samples/086DD730.pcm"

	.align 2
	.global ProgrammableWaveData_86DD740
ProgrammableWaveData_86DD740:
	.incbin "sound/programmable_wave_samples/086DD740.pcm"

	.align 2
	.global ProgrammableWaveData_86DD750
ProgrammableWaveData_86DD750:
	.incbin "sound/programmable_wave_samples/086DD750.pcm"
