#ifndef GUARD_SA1_UI_GRAPHICS_H
#define GUARD_SA1_UI_GRAPHICS_H

#define UIGFX_ASCII_CHARS              0
#define UIGFX_UI_ICON_SONIC            1
#define UIGFX_UI_ICON_TAILS            2
#define UIGFX_UI_ICON_KNUCKLES         3
#define UIGFX_UI_ICON_AMY              4
#define UIGFX_UI_ICON_RING             5
#define UIGFX_STGINTRO_ZIGZAG_SONIC    6
#define UIGFX_STGINTRO_ZIGZAG_TAILS    7
#define UIGFX_STGINTRO_ZIGZAG_KNUCKLES 8
#define UIGFX_STGINTRO_ZIGZAG_AMY      9
#define UIGFX_STGINTRO_CHAR_NAMES      10
#define UIGFX_STGRESULT_SONIC          11
#define UIGFX_STGRESULT_TAILS          12
#define UIGFX_STGRESULT_KNUCKLES       13
#define UIGFX_STGRESULT_AMY            14
#define UIGFX_STGRESULT_ACT12          15
#define UIGFX_STGRESULT_HEADLINE_BACK  16
#define UIGFX_STGNAMES_JP_0            17
#define UIGFX_18                       18
#define UIGFX_STGNAME_1                19
#define UIGFX_STGNAME_2                20
#define UIGFX_STGNAME_3                21
#define UIGFX_STGNAME_4                22
#define UIGFX_STGNAME_5                23
#define UIGFX_STGNAME_6                24
#define UIGFX_STGNAME_7                25
#define UIGFX_26                       26
#define UIGFX_27                       27
#define UIGFX_28                       28
#define UIGFX_29                       29
#define UIGFX_30                       30
#define UIGFX_31                       31
#define UIGFX_TIMER_DIGITS             32
#define UIGFX_OK                       33
#define UIGFX_34                       34
#define UIGFX_35                       35
#define UIGFX_36                       36
#define UIGFX_37                       37
#define UIGFX_38                       38
#define UIGFX_39                       39
#define UIGFX_40                       40
#define UIGFX_41                       41
#define UIGFX_42                       42
#define UIGFX_43                       43
#define UIGFX_CHAR_SELECT_OK           44
#define UIGFX_CHAR_SELECT_BLACK_BOX_2  45
#define UIGFX_CHAR_SP_STAGE_RINGS_BG   46
#define UIGFX_47                       47
#define UIGFX_48                       48
#define UIGFX_49                       49
#define UIGFX_50                       50
#define UIGFX_51                       51
#define UIGFX_52                       52
#define UIGFX_53                       53
#define UIGFX_54                       54
#define UIGFX_55                       55
#define UIGFX_56                       56
#define UIGFX_57                       57
#define UIGFX_58                       58
#define UIGFX_59                       59
#define UIGFX_60                       60
#define UIGFX_61                       61
#define UIGFX_62                       62
#define UIGFX_63                       63
#define UIGFX_64                       64
#define UIGFX_65                       65
#define UIGFX_66                       66
#define UIGFX_67                       67
#define UIGFX_68                       68
#define UIGFX_69                       69
#define UIGFX_70                       70
#define UIGFX_71                       71
#define UIGFX_72                       72
#define UIGFX_73                       73
#define UIGFX_74                       74
#define UIGFX_75                       75
#define UIGFX_76                       76
#define UIGFX_77                       77
#define UIGFX_78                       78
#define UIGFX_79                       79
#define UIGFX_80                       80
#define UIGFX_81                       81
#define UIGFX_82                       82
#define UIGFX_83                       83
#define UIGFX_84                       84
#define UIGFX_85                       85
#define UIGFX_86                       86
#define UIGFX_87                       87
#define UIGFX_88                       88
#define UIGFX_89                       89
#define UIGFX_90                       90
#define UIGFX_91                       91
#define UIGFX_92                       92
#define UIGFX_93                       93
#define UIGFX_94                       94
#define UIGFX_95                       95
#define UIGFX_96                       96
#define UIGFX_97                       97
#define UIGFX_98                       98
#define UIGFX_99                       99
#define UIGFX_100                      100
#define UIGFX_101                      101
#define UIGFX_102                      102
#define UIGFX_103                      103
#define UIGFX_104                      104
#define UIGFX_105                      105
#define UIGFX_106                      106
#define UIGFX_107                      107
#define UIGFX_108                      108
#define UIGFX_109                      109
#define UIGFX_110                      110
#define UIGFX_111                      111
#define UIGFX_112                      112
#define UIGFX_113                      113
#define UIGFX_114                      114
#define UIGFX_115                      115
#define UIGFX_116                      116
#define UIGFX_117                      117
#define UIGFX_118                      118
#define UIGFX_119                      119
#define UIGFX_120                      120
#define UIGFX_121                      121
#define UIGFX_122                      122
#define UIGFX_123                      123
#define UIGFX_124                      124
#define UIGFX_125                      125
#define UIGFX_126                      126
#define UIGFX_127                      127
#define UIGFX_OPTIONS                  128

#endif // GUARD_SA1_UI_GRAPHICS_H