#ifndef GUARD_PARAMETERS_STAGE_H
#define GUARD_PARAMETERS_STAGE_H

#define INITIAL_WATERLEVEL_ZONE_4_ACT_1 1546
#define INITIAL_WATERLEVEL_ZONE_4_ACT_2 1664

#define EGG_ROCKET_LAUNCH_MIN_X         1058
#define EGG_ROCKET_BOOSTER_DEPART_MAX_Y 5568
#define EGG_ROCKET_MIDDLE_DEPART_MAX_Y  3264

#endif // GUARD_PARAMETERS_STAGE_H
